spring:
  application:
    name: CinebhApp
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  session:
    jdbc:
      initialize-schema: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USER}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  port: 8080
  servlet:
    session:
      timeout: 20m
      tracking-modes: cookie
springdoc:
  api-docs:
    path: /api-docs
config:
  secret-key: ${JWT_KEY}